---
- name: "End play if distribution not suported"
  meta: end_host
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: "Check for gluster-exporter binary"
  stat:
    path: "{{ gluster_exporter_install_dir }}/gluster-exporter"
  changed_when: false
  register: gluster_exporter_install

- when: not gluster_exporter_install.stat.exists or gluster_exporter_force_install|bool
  block:
    - name: "Download gluster-exporter..."
      get_url:
        url: '{{ gluster_exporter_url }}'
        dest: '{{ gluster_exporter_install_dir }}/gluster-exporter'
        timeout: '60'
        mode: '0755'

- name: Creates directory
  file:
    path: /etc/gluster-exporter
    state: directory
    mode: 0755

- name: "Create systemd for gluster_exporter"
  template:
    src: 'gluster_exporter.service.j2'
    dest: '/etc/systemd/system/gluster_exporter.service'
    mode: '0640'
  notify: "restart gluster_exporter"

- name: "Create config file"
  template:
    src: 'gluster-exporter.toml.j2'
    dest: '/etc/gluster-exporter/gluster-exporter.toml'
    mode: '0640'
  notify: "restart gluster_exporter"

- name: BUGFIX https://github.com/gluster/glusterfs/issues/845
  copy:
    src: xfs_info
    dest: /usr/sbin/xfs_info
    owner: root
    group: root
    mode: '0755'

- name: "Enable and Start gluster_exporter.service"
  systemd:
    name: gluster_exporter
    state: started
    enabled: true
    daemon_reload: true
